language: php

php:
    - '7.1'
    - '7.2'
    - '7.3'
    - '7.4'

env:
    matrix:
        - PREFER_LOWEST="--prefer-lowest"
        - PREFER_LOWEST=""

install:
    - composer update --no-interaction $PREFER_LOWEST

script:
    - tests/automated/run-tests.php
