<?php

declare(strict_types=1);

namespace Daku\Nette\FormBlueprints;

use Tracy\Helpers;

/**
 * @var $this BlueprintsPanel
 */

?>
<h1>Form Blueprints</h1>
<div class="tracy-inner">
	<?php if ($this->forms): ?>
		<template>
			<style>
				<?php readfile(__DIR__ . '/assets/panel.css'); ?>
			</style>
			<div class="container">
				<aside>
					<h2>Added forms:</h2>
					<ul class="form-link-list">
						<?php foreach ($this->forms as $form): ?>
							<li>
								<span id="<?= $this->getFormId($form) ?>" title="<?= $this->getFormTitle($form) ?>" class="form-link<?= $this->getCurrentForm() === $form ? ' form-link-selected' : '' ?>">
									<?= $this->getFormName($form) ?>
								</span>
							</li>
						<?php endforeach; ?>
					</ul>
					<h2>Blueprint template:</h2>
					<select class="template-select">
						<?php foreach ($this->templates as $template): ?>
							<option value="<?= $template->getName() ?>"<?= $this->getCurrentTemplate() === $template ? ' selected' : '' ?>>
								<?= $template->getName() ?>
							</option>
						<?php endforeach; ?>
					</select>
					<h3>Template options:</h3>
					<div class="template-options">
						<?= $this->createTemplateOptions($this->getCurrentTemplate()) ?>
					</div>
				</aside>
				<main>
					<div class="tab-row">
						<div class="tab" data-tab-name="latte" data-target-hide=".detail" data-target-show=".detail-latte">
							Latte
						</div>
						<div class="tab" data-tab-name="css" data-target-hide=".detail" data-target-show=".detail-css">
							CSS
						</div>
						<div class="tab" data-tab-name="preview" data-target-hide=".detail" data-target-show=".detail-preview">
							Preview
						</div>
						<div class="spinner" hidden><span></span></div>
					</div>
					<?php [$file, $latteEscaped, , $selectRangeListHtml] = $this->prepareBlueprint($this->getCurrentForm(), $this->getCurrentTemplate()) ?>
					<div class="detail detail-latte" hidden>
						<a href="#" class="copy-button">Copy to clipboard</a> |
						<a href="<?= Helpers::editorUri($file) ?>" class="html-editor-link" title="<?= $file ?>">Open in editor</a>
						<span class="tooltip-copied" hidden>Copied</span>
						<div title="After selecting press Ctrl+C to copy">
							Select individual: <span class="select-range-list"><?= $selectRangeListHtml ?></span>
						</div>
						<pre class="auto-resizable"><code class="language-latte"><?= $latteEscaped ?></code></pre>
					</div>
					<div class="detail detail-preview auto-resizable" hidden></div>
					<div class="detail detail-css" hidden>
						<a href="#" class="copy-button">Copy to clipboard</a>
						<span class="tooltip-copied" hidden>Copied</span>
						<pre class="auto-resizable"><code class="language-latte"><?= htmlspecialchars($this->getCurrentTemplate()->getStyles()) ?></code></pre>
					</div>
				</main>
			</div>
			<iframe class="prism-iframe" data-srcdoc='<script data-manual src="https://cdn.jsdelivr.net/combine/npm/prismjs@1.25.0,npm/prismjs@1.25.0/components/prism-markup-templating.min.js,npm/prismjs@1.25.0/components/prism-php.min.js,npm/prismjs@1.25.0/components/prism-latte.min.js,npm/prismjs@1.25.0/plugins/keep-markup/prism-keep-markup.min.js"></script>'></iframe>
		</template>
		<script>
			(function () {
				<?php readfile(__DIR__ . '/assets/panel.js'); ?>
			})();
		</script>
		<style class="tracy-debug">
			div#tracy-debug #tracy-debug-panel-Daku-Nette-FormBlueprints-BlueprintsPanel {width: 800px;height: 550px;max-width: initial;max-height: initial; overflow: hidden}
			body#tracy-debug #tracy-debug-panel-Daku-Nette-FormBlueprints-BlueprintsPanel {height: 100vh; overflow: hidden}
		</style>
	<?php else: ?>
		<p>No forms added to the panel.</p>
	<?php endif; ?>
</div>
